# Generated by Django 5.1.3 on 2024-11-13 16:40

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GioiThieu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tieu_de', models.CharField(max_length=255)),
                ('noi_dung', django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
        migrations.CreateModel(
            name='LienHe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('hinh_anh', models.ImageField(default='images/slider/no-image.jpg', upload_to='images/slider')),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('thu_tu', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['thu_tu'],
            },
        ),
        migrations.CreateModel(
            name='ThuongHieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thuong_hieu', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('hinh_anh', models.ImageField(default='images/thuong-hieu/no-image.jpg', upload_to='images/thuong-hieu')),
            ],
        ),
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=255)),
                ('ten_khong_dau', models.CharField(blank=True, max_length=255, null=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('hinh_anh', models.ImageField(default='images/danh-muc/no-image.jpg', upload_to='images/danh-muc')),
                ('danh_muc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_store.danhmuc')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.CharField(max_length=255)),
                ('ten_khong_dau', models.CharField(blank=True, max_length=255, null=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(max_length=255)),
                ('gia_ban', models.BigIntegerField(default=0)),
                ('gia_goc', models.BigIntegerField(default=0)),
                ('thong_so_ky_thuat', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.danhmuc')),
                ('thuong_hieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.thuonghieu')),
            ],
        ),
        migrations.CreateModel(
            name='HinhSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(default='images/san-pham/no-image.jpg', max_length=200, upload_to='images/san-pham')),
                ('dai_dien', models.BooleanField(default=False)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.sanpham')),
            ],
            options={
                'ordering': ['-dai_dien'],
            },
        ),
    ]
