# Generated by Django 5.1.1 on 2024-12-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0002_alter_donhang_ma_don_hang'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='ma_don_hang',
            field=models.CharField(default='DH20241206092847', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
