# Generated by Django 5.1.1 on 2024-12-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0003_donhang_ghi_chu_alter_donhang_ma_don_hang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='ma_don_hang',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
