# Generated by Django 4.2.17 on 2024-12-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0005_alter_khuyenmai_ma_khuyen_mai_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='khuyenmai',
            table='khuyen_mai',
        ),
    ]
