# Generated by Django 4.2.17 on 2024-12-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0006_alter_khuyenmai_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='khuyenmai',
            table='khuyenmai',
        ),
    ]
