# Generated by Django 4.2.17 on 2024-12-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0007_alter_khuyenmai_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khuyenmai',
            name='ti_le_khuyen_mai',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterModelTable(
            name='khuyenmai',
            table=None,
        ),
    ]
