# Generated by Django 5.1.1 on 2024-11-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho', models.CharField(blank=True, max_length=100, null=True)),
                ('ten', models.CharField(blank=True, max_length=50, null=True)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('ten_dang_nhap', models.CharField(max_length=100, unique=True)),
                ('mat_khau', models.CharField(max_length=200)),
                ('dia_chi', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
